### ISSUE TITLE
add names to lead and snacks/scribe in PEPmeeting?

### ISSUE THREAD

**Issue by iantaylor-NOAA** [nwfsc-assess/PEPtools#2]
Current list of names is focused on those in Seattle with non-FTE folks being included in snacks list but not potential leaders (also Hastie left off and Owen potential for snacks but not lead)
```
  leads = c("Brian", "Chantel", "Jason", "John", "Kelli", "Kristin", "Ian", "Melissa", "Vlada"),
  snacks = c("Josh", "Owen", "Christine", "Kathryn")
```
During this 100% remote period, I think it would be good to expand the leads list to include Aaron and Andi and maybe limit the former snacks (now scribe) role to only apply to the NOAA FTEs as well.

**Comment by kellijohnson-NOAA** [comment]
I am not certain I get the logic behind limiting the "snacks" / "scribe" role.

**Comment by kellijohnson-NOAA** [comment]
b0fc48e

**Comment by iantaylor-NOAA** [comment]
Thanks for the change @kellijohnson-NOAA.
My thinking on limiting the scribe role was mostly that some of those folks weren't present as often, but your change looks good to me and we can always revisit as needed in the future.
