### ISSUE TITLE
Vectorize and create Lead, Scribe, and Snack picks for the future

### ISSUE THREAD

**Issue by John-R-Wallace-NOAA** [nwfsc-assess/PEPtools#3]
Now that we no longer wait to see who absent before the code is run, I can vectorize the code using dates() math and pick all three persons: Lead, Scribe, and Snack.

It was a pain when I ran the code for a series of dates some time back.

**Comment by kellijohnson-NOAA** [comment]
Don't overthink things. We don't even really need this code to begin with. We could all just sign up for dates when it works best for our schedule.
